const EErros = {
    PRODUCT_NOT_IN_CART: 1,
    CART_DOESNT_EXIST: 2,    
    MONGO_CONNECT_FAIL: 3,
    AUTHENTICATION_ERROR: 4,
    AUTHORIZATION_ERROR: 5,
    INTERNAL_SERVER_ERROR: 6,
    ERROR_CREATING_PRODUCT: 7
}

export default EErros;